[package]
name = "linura-observation-control"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
linura-core = { path = "../linura-core" }
linura-graph = { path = "../linura-graph" }
linura-observation = { path = "../linura-observation" }
linura-protocol = { path = "../linura-protocol" }
linura-provider-sdk = { path = "../linura-provider-sdk" }

[lints]
workspace = true
