[package]
name = "linura-persistence-sqlite"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
linura-core = { path = "../linura-core" }
linura-transaction = { path = "../linura-transaction" }
rusqlite = { version = "0.37", features = ["bundled", "functions"] }
rustix = { version = "1.1", features = ["fs"] }
sha2 = "0.10"

[lints]
workspace = true
