[package]
name = "linura-dbus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
blocking = "=1.7.0"
linura-core = { path = "../linura-core" }
linura-graph = { path = "../linura-graph" }
linura-observation = { path = "../linura-observation" }
linura-observation-control = { path = "../linura-observation-control" }
linura-planner = { path = "../linura-planner" }
linura-protocol = { path = "../linura-protocol" }
zbus = { version = "=5.19.0", default-features = false, features = ["async-io", "blocking-api"] }

[lints]
workspace = true
