[package]
name = "linura-provider-sdk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
linura-core = { path = "../linura-core" }
linura-protocol = { path = "../linura-protocol" }

[lints]
workspace = true
