[package]
name = "linurad"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
linura-control = { path = "../../crates/linura-control" }
linura-policy = { path = "../../crates/linura-policy" }

[lints]
workspace = true
