[package]
name = "linurad"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
linura-dbus = { path = "../../crates/linura-dbus" }
linura-linux-observation = { path = "../../crates/linura-linux-observation" }
linura-observation-control = { path = "../../crates/linura-observation-control" }

[lints]
workspace = true
