[package]
name = "linura-verifier-systemd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
linura-core = { path = "../../crates/linura-core" }
linura-observation = { path = "../../crates/linura-observation" }
linura-provider-sdk = { path = "../../crates/linura-provider-sdk" }

[lints]
workspace = true
