[package]
name = "linura-control"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
linura-core = { path = "../linura-core" }
linura-graph = { path = "../linura-graph" }
linura-observation = { path = "../linura-observation" }
linura-observation-control = { path = "../linura-observation-control" }
linura-planner = { path = "../linura-planner" }
linura-protocol = { path = "../linura-protocol" }

[lints]
workspace = true
